apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-acc
  namespace: emojivoto
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaler-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "update", "list"]
- apiGroups: [""]
  resources: ["events", "pods"]
  verbs: ["create", "patch", "update", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scaler-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scaler-role
subjects:
- kind: ServiceAccount
  name: scaler-acc
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler
  namespace: emojivoto
  labels:
    app: scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaler
  template:
    metadata:
      labels:
        app: scaler
    spec:
      containers:
      - name: scaler
        image: tarunpothulapati/scaler
        imagePullPolicy: Always
      serviceAccountName: scaler-acc
---